### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by edomora97** [TheEntropics/TeamSpeak3-stats#1]
Lista delle cose da implementare:
- [x] Classi degli eventi @Lucco97 
- [x] Parser & Regex @edomora97
- [x] FileReader @MarcoCivettini @edomora97
- [x] CacheService @edomora97
- [x] Database @edomora97
- [x] Controller @edomora97
- [x] MainAnalyzer @edomora97
- [x] BaseAnalyzer @edomora97
- [x] Analizzatori [link](https://docs.google.com/document/d/1bb-kLUBqBeAh_FV2lgaTnmtBEkw7H5Qn6fACg27i7sQ)
  - [x] UptimeAnalyzer @edomora97
  - [x] OnlineAnalyzer @edomora97
  - [x] DailyAnalyzer @edomora97
  - [x] DisconnectedAnalyzer @edomora97
  - [x] ConnectedAnalyzer @edomora97
  - [x] UsernameAnalyzer
  - [x] ~~IPAnalyzer~~
  - [x] FileAnalyzer @edomora97
  - [x] ChannelAnalyzer
- [x] Visualizzatore delle statistiche
